# Generated by Django 6.1.1 on 2026-09-24 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_recurringtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_hash', models.CharField(max_length=128)),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset')], max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'purpose', 'is_used'], name='tracker_ema_email_e03347_idx'), models.Index(fields=['expires_at'], name='tracker_ema_expires_53f6c9_idx')],
            },
        ),
    ]
