# Generated by Django 6.1.1 on 2026-09-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registration'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('account_delete', 'Account Deletion')], max_length=20),
        ),
    ]
