# Generated by Django 6.1.1 on 2026-09-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_emailotp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='pending_password_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
